//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEncryptSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public int id_wallet { get; set; }
        public string Name_wallet { get; set; }
        public string description_Wallet { get; set; }
        public Nullable<int> id_client { get; set; }
    
        public virtual client client { get; set; }
    }
}
